### ISSUE TITLE
Doesn't work with fitbit

### ISSUE THREAD

**Issue by phazei** [artdarek/oauth-4-laravel#139]
Seems there was a bug that breaks the signature that was fixed in https://github.com/Lusitanian/PHPoAuthLib/pull/309
but that's only available on dev-master, and this is currently using ~0.3

**Comment by phazei** [comment]
In case anyone needs help with the same issue, I was able to fix it by aliasing the version of the latest PHPoAuthLib in my composer file like so:

    "lusitanian/oauth": "dev-master as 0.3.5",

**Comment by davidsneal** [comment]
Thanks for this @phazei !!
