### ISSUE TITLE
Facebook auth does not return email

### ISSUE THREAD

**Issue by arifw3** [artdarek/oauth-4-laravel#154]
please help.
İts only return
array(2) { ["name"]=> string(10) "Arif Erzin" ["id"]=> string(17) "10153177435559690" }

**Comment by omssharma** [comment]
Same problem with me. I noticed when I use fb api version 2.3, it works. And when I use fb api version 2.4, it doesn't work. Help needed..

**Comment by omssharma** [comment]
In the controller, use $result = json_decode( $fb->request( '/me?fields=id,name,email' ), true );
instead of $result = json_decode( $fb->request( '/me' ), true );

**Comment by arifw3** [comment]
It works for the examples I tried.

**Comment by omssharma** [comment]
Great !!

**Comment by arifw3** [comment]
İs email possible in twitter api?
