### ISSUE TITLE
Twitter auth does not return email

### ISSUE THREAD

**Issue by arifw3** [artdarek/oauth-4-laravel#155]
Is get email possible in twitter api?

**Comment by mikeslim7** [comment]
Unfortunately, not as "default" as you expected. I just leart this today as well. See this long thread: https://twittercommunity.com/t/how-to-get-email-from-twitter-user-using-oauthtokens/558/188 and you will also find this link helpful: http://docs.fabric.io/android/twitter/request-user-email-address.html
You need to apply for that access.
