### ISSUE TITLE
Call to undefined method OAuth::consumer()

### ISSUE THREAD

**Issue by benwigley** [artdarek/oauth-4-laravel#17]
The plugin is working perfectly in development, but when I push to production (using Amazon EC2) the plugin is not found in my controller:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException
Call to undefined method OAuth::consumer()
```

Another guy was having the same issue here and as yet no one has resolved it.
http://forums.laravel.io/viewtopic.php?id=14560

Any help would be much appreciated, thanks.

**Comment by dmyers** [comment]
If anyone runs into this, you could possibly have the `OAuth` PHP extension installed without knowing it like I did on AWS Elastic Beanstalk which would collide with this package's alias. I ended up just using the full namespace path myself like others suggested.

**Comment by carld** [comment]
Ya, same here

```
-               $googleService = OAuth::consumer( 'Google' );
+               $googleService = Artdarek\OAuth\Facade\OAuth::consumer( 'Google' );
```
