### ISSUE TITLE
(Facebook Login) Failed to request resource. HTTP Code: HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by chhumsina** [artdarek/oauth-4-laravel#173]
![1](https://cloud.githubusercontent.com/assets/3894767/14070264/8323e370-f4ce-11e5-8e78-6785d418ce97.PNG)
![2](https://cloud.githubusercontent.com/assets/3894767/14070263/82ecc728-f4ce-11e5-9a88-bbb514c538d3.PNG)

Thanks you

**Comment by FebriPratama** [comment]
got same issue, it seems that the requestAccessToken method has been deprecated due fb api update, so I just requesting and set access token manually with curl.

**Comment by chhumsina** [comment]
Hi @FebriPratama ,

Could you please paste the full sample?

Thanks you :)

**Comment by FebriPratama** [comment]
@chhumsina 
Here is the sample

`  
    public function Loginfb()
    {

	    // get data from input
	    $code = Input::get( 'code' );

		$OAuth = new OAuth();
		$OAuth::setHttpClient('CurlClient');

	    // get fb service
	    $fb = $OAuth::consumer( 'Facebook' , Input::get('redirectUri'));

	    // if code is provided get user data and sign in
	    if ( !empty( $code ) ) {

	        // This was a callback request from facebook, get the token
	        $token = $fb->requestAccessToken( $code );

	        //$token = json_decode( $token, true );

	        // Send a request with it
	        $result = json_decode( $fb->request( '/me?fields=name,email' ), true );

               dd($result);

	    }
	    // if not ask for permission first
	    else {
	        // get fb authorization
	        $url = $fb->getAuthorizationUri();

	        // return to facebook login url
	         return Redirect::to( (string)$url );
	    }

`

**Comment by chhumsina** [comment]
@FebriPratama 

After putting you full sample code I get this:

**Comment by FebriPratama** [comment]
@chhumsina download cacert.pem [http://curl.haxx.se/ca/cacert.pem](url) then paste it to your php/extras/ssl folder, ex :  xampp/php/extras/ssl . then restart ur server

**Comment by chhumsina** [comment]
@FebriPratama 

I already added and it's working with this certificate but another issue is appeared.
![capture](https://cloud.githubusercontent.com/assets/3894767/15316452/3f86b7a0-1c47-11e6-92a6-5e77b3e4ab06.PNG)

Sorry for interrupt you again
Thank you :)

**Comment by mrbarde** [comment]
@FebriPratama I'm having the same problem as @chhumsina

**Comment by mrbarde** [comment]
@FebriPratama @chhumsina think i figured it out, you can't request for an access token more than once so the person will have to rerun the login process again, to avoid this try wrapping the code snippet for requesting access token in a try catch scope like so.

```
try{
    // This was a callback request from facebook, get the token
    $token = $fb->requestAccessToken( $code );
    // Send a request with it
    $result = json_decode( $fb->request( '/me' ), true );
}catch(Exception $e){
    return Redirect::to('auth/login')->with("sys_message", ["body"=>"An error occurred please try again."])
}

```
Hope this helped.
