### ISSUE TITLE
TokenResponseException

### ISSUE THREAD

**Issue by joshbrw** [artdarek/oauth-4-laravel#21]
When trying to get a access token using the `requestAccessToken($code)` method, I am getting this returned

```php
{"error":{"type":"OAuth\\Common\\Http\\Exception\\TokenResponseException","message":"Failed to request resource.","file":"\/Users\/josh\/Sites\/richmedia\/vendor\/lusitanian\/oauth\/src\/OAuth\/Common\/Http\/Client\/StreamClient.php","line":62}}
```

Any ideas?

**Comment by FeliciousX** [comment]
@elcct how exactly did you switch to CurlClient instead? :D

**Comment by FeliciousX** [comment]
@Cyruxx in order to use CurlClient instead of the default, StreamClient , specifiy it before you call the `OAuth::consumer()` method.

Here's my example:-
```
public function loginWithBox()
{
...
$OAuth = new OAuth();
$OAuth::setHttpClient('CurlClient');
$box = $OAuth::consumer('Box');
...
}
```

Although this is abit old, I hope this helps for any future readers :)

**Comment by herlon214** [comment]
:+1:

**Comment by davidsneal** [comment]
@FeliciousX it helped me, thanks!

**Comment by FeliciousX** [comment]
@davidsneal welcome! Glad to be of help :smile:

**Comment by akaramires** [comment]
@FeliciousX thank you!

**Comment by SerdarSanri** [comment]
I just found out that for Facebook, if you set your application Desktop application, token fails and you get the same error. After disabling Desktop/Native app checkbox everything worked fine.

**Comment by rrbailey89** [comment]
@FeliciousX @Cyruxx where is the location of the file that those edits should be made? I cant find those lines of code anywhere :(

**Comment by FeliciousX** [comment]
@rrbailey89 anywhere on your codebase just before you call `OAuth::consumer()` as stated in my [comment above](https://github.com/artdarek/oauth-4-laravel/issues/21#issuecomment-71971502)

**Comment by rrbailey89** [comment]
@FeliciousX that's the thing I'm using phpbb 3.1.8 I have looked thru probably over 50 different files for that line of code and in not seeing it. I was hoping someone here might be able to tell me where the edit about be made. 

This is the forum software I'm using https://www.phpbb.com/files/release/phpBB-3.1.8.zip
