### ISSUE TITLE
PHP Fatal error:  Class 'Patchwork\Utf8\Bootup' not found in /var/www/msg/bootstrap/autoload.php on line 46

### ISSUE THREAD

**Issue by FMaz008** [artdarek/oauth-4-laravel#30]
I followed the installation instructions, added the dependency in composer.json, then attempted to run composer update command, both without and with sudo.

I get this:

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing lusitanian/oauth (v0.2.5)
  Downloading: 100%         
- Installing artdarek/oauth-4-laravel (dev-master 066e483)
  Downloading: 100%         
- Removing laravel/framework (v4.1.18)
- Removing classpreloader/classpreloader (1.0.1)
- Removing d11wtq/boris (v1.0.8)
- Removing ircmaxell/password-compat (1.0.3)
- Removing filp/whoops (1.0.10)
- Removing jeremeamia/superclosure (1.0.1)
- Removing nikic/php-parser (v0.9.4)
- Removing monolog/monolog (1.7.0)
- Removing nesbot/carbon (1.8.0)
- Removing patchwork/utf8 (v1.1.17)
- Removing phpseclib/phpseclib (0.3.5)
- Removing predis/predis (v0.8.5)
- Removing stack/builder (v1.0.1)
- Removing swiftmailer/swiftmailer (v5.0.3)
- Removing symfony/browser-kit (v2.4.1)
- Removing symfony/css-selector (v2.4.1)
- Removing symfony/dom-crawler (v2.4.1)
- Removing symfony/http-kernel (v2.4.1)
- Removing symfony/event-dispatcher (v2.4.1)
- Removing symfony/http-foundation (v2.4.1)
- Removing symfony/debug (v2.4.1)
- Removing symfony/filesystem (v2.4.1)
- Removing symfony/console (v2.4.1)
- Removing symfony/finder (v2.4.1)
- Removing symfony/process (v2.4.1)
- Removing symfony/routing (v2.4.1)
- Removing psr/log (1.0.0)
- Removing symfony/translation (v2.4.1)
  lusitanian/oauth suggests installing symfony/http-foundation (Allows using the Symfony Session storage backend.)
  lusitanian/oauth suggests installing predis/predis (Allows using the Redis storage backend.)
  Writing lock file
  Generating autoload files
  PHP Fatal error:  Class 'Patchwork\Utf8\Bootup' not found in /var/www/msg/bootstrap/autoload.php on line 46
  Script php artisan clear-compiled handling the post-update-cmd event returned with an error
  
  [RuntimeException]  
  Error Output: PHP Fatal error:  Class 'Patchwork\Utf8\Bootup' not found in  
  /var/www/msg/bootstrap/autoload.php on line 46                               

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [packages1] ... [packagesN]

**Comment by jorwan** [comment]
the only require key that i have in my composer.json is:

	"require": {
		"laravel/framework": "5.0.*",
                "laravel/socialite": "~2.0",
		"zizaco/entrust": "1.4.0",
		"intervention/image": "2.0.11",
		"whatsapp/chat-api": "v2.5",
		"hybridauth/hybridauth": "dev-3.0.0-Remake",
		"dinesh/bugonemail": "5.0.*@dev",
		"anlutro/curl": "0.6.2",
    	        "fzaninotto/faker": "1.3.*@dev",
    	        "phpunit/phpunit": "4.0.*",
		"laracasts/generators": "1.1.1"
	},

...and still have the same error. : /
