### ISSUE TITLE
Question regarding storage configuration

### ISSUE THREAD

**Issue by dlabey** [artdarek/oauth-4-laravel#40]
If we have Laravel set to use Redis for sessions and our storage is set to Session, will this use Redis?

**Comment by dlabey** [comment]
Thank you for the answer, seeing the interface I see how it is done.

**Comment by millar** [comment]
In case anyone else stumbles across this, here is my solution as suggested by @maknz.

The class I created looked like so:
```php
<?php

namespace OAuth\Common\Storage;

use Predis\Client as Predis;

class LaravelRedisStorage extends Redis implements TokenStorageInterface {

    public function __construct()
    {
        $this->redis = \Redis::connection();
        $this->key = 'oauth_user_tokens';
        $this->stateKey = 'oauth_user_states';
        $this->cachedTokens = array();
        $this->cachedStates = array();
    }

}
```

I autoloaded this in my `composer.json` file and set it to be used in `app/config/packages/artdarek/oauth-4-laravel/config.php` like so:
```php
/**
 * Storage
 */
'storage' => 'LaravelRedisStorage',
```
