### ISSUE TITLE
How to use your wrapper with Lusitanian/PHPoAuthLib?

### ISSUE THREAD

**Issue by anam-hossain** [artdarek/oauth-4-laravel#5]
Hi Artdarek, I have downloaded and using your Oauth rapper with Laravel 4 and I am successfully generating the wrapper class. However , i am struggling to use this object with Lusitanian/PHPoAuthLib. Do you have any example?

I am trying to use Twitter.
## 

Anam

**Comment by kjtigue** [comment]
hi,

im trying to oauth microsoft using artdarek in laravel 4
the error is

"createService" not found
or maybe my serviceFactory is wrong


here is my code

public function index(){
		$storage = new Session();
		$code = Input::get( 'code' );
		$serviceFactory = OAuth::consumer( 'Microsoft' );
		$microsoft = $serviceFactory->createService('microsoft', $credentials, $storage, array('basic'));
			
		if (!empty($code)) {
			
			$token = $microsoft->requestAccessToken($code);
		    Session::put("stoken",$token->getAccessToken());

		    $result = json_decode($microsoft->request('/account/info'), true);
		    // return Redirect::to('sky_getfile/index');
		    var_dump($result);
		
		} elseif (!empty($_GET['go']) && $_GET['go'] === 'go') {
	 		$url = $microsoft->getAuthorizationUri();
		    return Redirect::to( (string)$url );
		} else {
			$url = Request::url() . '?go=go';
		    return Redirect::to($url);
		}
	}

**Comment by cityzen** [comment]
Hi kjtigue, 

Are you using the  artdarek/oauth-4-laravel package? if so, You'll want to approach it a bit differently, something like this:

```
public function index()
{
  $microsoft = OAuth::consumer('microsoft');

  $code = Input::get('code');

  if(!empty($code))
  {
    $token = $microsoft->requestAccessToken($code);

    if ($token->isExpired() === TRUE)
    {
      $microsoft->refreshAccessToken($accessToken);
    }

    $result = json_decode($microsoft->request('/account/info'), true);
    dd($result);
  }
}
```

You'll probably have to tweak that a bit for your use (completely untested). if you look at the readme for oauth-4-laravel [here](https://github.com/artdarek/oauth-4-laravel), scroll down and you'll implementations for facebook, twitter, google, etc and compare those to the examples [here](https://github.com/Lusitanian/PHPoAuthLib/tree/master/examples), you can piece together how it works.

**Comment by kjtigue** [comment]
can i ask i am authenticating my box application and it seems like i have to use url to process requests. is there a more faster way? i didnt find any box library in github.

and example if i am authenticated to box using artdarek can i use the box api without authenticating it again?

**Comment by kjtigue** [comment]
by the way thanks cityzen :)

**Comment by cityzen** [comment]
No problem. It looks like there was a Box SDK for v1 at some point but it's gone now. Your best bet is probably just using the api endpoints.

As far as authentication, I used the artdarek package as a basis to write my own Laravel service provider within my own namespace. I added a Storage for Database/Eloquent and Laravel Session and also included the ability to write my own service interfaces or extend/overwrite existing ones. I will see if I can make it modular enough to run as an independent package.

**Comment by kjtigue** [comment]
what do you mean api endpoints? do they have a reference? i really find it hard to trace the urls..

**Comment by kjtigue** [comment]
that would be awesome if you could :+1: @cityzen

**Comment by kjtigue** [comment]
do you mean this one?
windows box sdk?

https://developers.box.com/box-windows-sdk-tutorial/

can i use this?

**Comment by cityzen** [comment]
They have a list of SDKs/Libraries [here](https://trello.com/c/RvAGjCA5/36-sdks) if you haven't seen it but it seems like the PHP one is lacking: [PHP Box View PHP SDK](https://github.com/donutdan4114/box-view-api)

What are you trying to do? It sounds like you want to authenticate against box, store your tokens locally so users can set it and forget it. I am doing something similar with Stripe Connect and storing the tokens (encrypted) in the database.

It seems like the documentation [here](https://developers.box.com/docs/) is pretty thorough.

**Comment by kjtigue** [comment]
wow thanks :) but yeah i am a web developer and in my application i really have to use php. bdw is the box content and box view different? 

this is what i am aiming to achieve:
upload,download,delete,search => files
create and delete  => folders

**Comment by kjtigue** [comment]
using laravel 4, artdarek and php

thanks for helping me out @cityzen  :) :+1: 
im really new in using api

**Comment by cityzen** [comment]
No problem, we're all new at something all the time :)

I found this, which may be a huge help to you: [https://github.com/adammbalogh/box-php-sdk](https://github.com/adammbalogh/box-php-sdk)

There is a file management system called flysystem that I thought may have a box integration but this guy posted and said he was basically writing his own box php SDK.

**Comment by kjtigue** [comment]
wowww... thankssss so much @cityzen  :+1:  :+1:

**Comment by kjtigue** [comment]
have you encountered this error?

Class 'AdammBalogh\KeyValueStore\Adapter\NullAdapter' not found

**Comment by kjtigue** [comment]
am i doing this right? :)

public function index(){
		//using artdarek for authentication	
		$storage = new Session();
		$code = Input::get( 'code' );
	    $boxService = OAuth::consumer('Box');

		if (!empty($code)) {
			$state = isset($_GET['state']) ? $_GET['state'] : null;

		    $t = $boxService->requestAccessToken($code,$state);
		    $token = $t->getAccessToken(); 
		    Session::put("btoken",$token);
		    
		    $keyValueStore = new KeyValueStore(new NullAdapter());
		    $oAuthClient = new OAuthClient($keyValueStore,$boxService);
		    $oAuthClient->authorize();
		    $contentClient = new ContentClient(new ApiClient($token), new UploadClient($token));
		    $apiKey = '5jy9vikaqkb6yrutdt2nn6nbp7411fg1';
		    $viewClient = new ViewClient(new ApiClient($apiKey), new UploadClient($apiKey));
		   
		    Session::out("contentClient",$contentClient);
		    Session::put("viewClient",$viewClient);

		    $result = json_decode($boxService->request('/users/me'), true);
		    $files = json_decode($boxService->request('/folders/0?fields=item_collection,name'), true);
		    Session::put('files',$files);
		     
		     return Redirect::to('box_getfile/index3');
		
		} elseif (!empty($_GET['go']) && $_GET['go'] === 'go') {
	 		$url = $boxService->getAuthorizationUri();
		    return Redirect::to( (string)$url );
		} else {
			$url = Request::url() . '?go=go';
		    return Redirect::to($url);
		}

**Comment by kjtigue** [comment]
my content and view client are null. 
but artadek can already authenticate it for me. right? 
should i authenticate them again?
i dont see anything like setAccessToken on OauthClient in Box

im so confused right now. haha

**Comment by cityzen** [comment]
If you're just integrating with Box I would skip using the artdarek package
for now entirely. The other package has the ability to authenticate with
OAuth as you can see here:
https://github.com/adammbalogh/box-php-sdk#authorization

**Comment by kjtigue** [comment]
no im working on 3 clouds
google drive,dropbox and box
now i have an error
"access token cannot be null"
should my access token be from artdarek or from box sdk/api?

sorry if i have so many questions
been coding by myself and i need some sort of guidance :)

**Comment by kjtigue** [comment]
i really dont know how to use this one..
it took me some time already still no chance :/

https://github.com/adammbalogh/box-php-sdk#authorize

**Comment by padom** [comment]
Hi artdarek,

i have tried your code for login with facebook and twitter, but i always get ErrorException for facebook Undefined index: access_token 
on this line $token->setAccessToken($data['access_token']);

for twitter Undefined index: oauth_token on this line
 $token->setRequestToken($data["oauth_token"]);

if i dump the given variable to both with dd($data) i see access_token and oauth_token

i don't know what i can do, please can you help me ?

I use laravel 4.1.31 and php version is 5.3

Sorry for my bad english.

**Comment by padom** [comment]
Hi to all,

anyone ?

**Comment by herlon214** [comment]
The same problem here =/

**Comment by peiphb02** [comment]
I have the same problem. Please help! It is really important, because I use your package in production!

**Comment by nikhilrapr** [comment]
Hi artdarek,

I am getting exception 'ErrorException' with message 'Undefined index: access_token' in vendor/lusitanian/oauth/src/OAuth/OAuth2/Service/Facebook.php:171

issue in my laravel site (version 4).

Please help me to sort out this
