### ISSUE TITLE
Token not found in session - Twitter

### ISSUE THREAD

**Issue by anam-hossain** [artdarek/oauth-4-laravel#7]
Hi Artdarek,

I have successfully able to integrate Google, Facebook, LinkedIn etc using your Oauth Laravel 4 Wrapper. However, I am stuck with Twitter since yesterday. Twitter is returning Oauth token and Oauth verifier when i have requested. 
http://example.dev/twitter?oauth_token=4gioDdSxM2dOb6vuYHQaWzhT3dXka4lVd7mpi3jjVQ&oauth_verifier=syO0Dko8FUMJz2K1yAMtuKF9AJc8q2jAJYWC2Guu7Cw

However, I am receiving the following error.

```
OAuth \ Common \ Storage \ Exception \ TokenNotFoundException
Token not found in session, are you sure you stored it?
```

The following code is throwing the exception:
```php
$token = $twitterService->getStorage()->retrieveAccessToken('Twitter');
```

### My configuration for Twitter:
```php
'Twitter' => array(
            'client_id'   		=> 'sdfsaQt7W8sdafs',
            'client_secret' 	=> 'sdfasdf9ag5nMq4lHBcBeurPrsfasdfa',
        ),	
```	

May be i am missing something in configuration.

Sorry to bug you again about this...

**Comment by tomsowerby** [comment]
I'm also having issues with the old OAuth\Common\Storage\Exception\TokenNotFoundException
My code was running the example code from the readme.

I switched it to use Lusitanian/PHPoAuthLib as suggested by @sandboxdigital, got a few class not found and invalid request exceptions until following the posts by @epsilon1983.

When I didn't have the callback set in the twitter developer site settings I was getting a different error:
OAuth\Common\Http\Exception\TokenResponseException Failed to request resource

So, with the Lusitanian/PHPoAuthLib AND the callback set in the settings. I'm back to getting the TokenNotFoundException.

Facebook and Google work perfectly, but Twitter seems to have issues.

**Comment by potsky** [comment]
I can make Twitter work ONLY if I put a callback URL in the Twitter App Console. If I remove the callback URL from the Twitter App, I reach a `TokenNotFoundException` too.
